theme: jekyll-theme-cayman

title: My Blog on Machine/Deep Learning
description: This is a blog about different topics in machine learning or deep learning

social:
   github: tesfagabir
   linkedin: tesfagabir
   email: tesfagabir@users.noreply.github.com
