theme: jekyll-theme-cayman


title: Tes Blog
description: A blog on data science and machine/deep learning topics

social:
   github: tesfagabir
   linkedin: tesfagabir
   email: tesfagabir2004@gmail.com
