theme: jekyll-theme-cayman


title: My Blog
description: Topics on data science and machine/deep learning

show_downloads: "true"
site.github.is_project_page: "true"

social:
   github: tesfagabir
   linkedin: tesfagabir
   email: tesfagabir2004@gmail.com
